### PR TITLE
Fix errors in contributing.rst for setup

### PR DESCRIPTION
**Pull request by JasonWeill**
Fix errors in setup docs: removes a redundant `pip` command, and updates the repository's punctuation.

### CODE REVIEW

**Comment by davidbrochart** [comment]
> removes a redundant `pip` command

Why is it redundant?

**Comment by JasonWeill** [comment]
Line 32 mentions that users need to install both `node` and `pip` before starting with installation. Line 34 starts, "Once you have installed the dependencies above …". Either we need to delete line 32 and start the instructions with installing both `node` and `pip`, or the documentation needs to presume, at the start of the code block, that the user has already installed both `node` and `pip`. The previous version of this file included instructions to install `pip`, but not `node`.

**Comment by davidbrochart** [comment]
But `pip install --upgrade pip` *upgrades* `pip`, right?

**Comment by JasonWeill** [comment]
It does; is that required? As long as the user has supported versions of `pip` and `node`, they should be OK to start with the command after the "upgrade `pip`" command.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
