### PR TITLE
Bump pycrdt-websocket>=0.14.0,<0.15.0

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by krassowski** [comment]
Maybe rebasing here could help to fix the failing tests?

**Comment by davidbrochart** [comment]
> Maybe rebasing here could help to fix the failing tests?

It's a PR against the `2.x` branch, so no need to rebase.

**Review by Zsailer — APPROVED** [review]

**Comment by Zsailer** [comment]
Thanks, @davidbrochart

**Review by jzhang20133 — APPROVED** [review]

**Comment by jzhang20133** [comment]
Thanks, @davidbrochart! In our recent test, after upgrading to this version, we stop seeing rapid memory growth while using RTC.

**Comment by davidbrochart** [comment]
Interesting, it's hard to say what exactly is responsible for this, it may be the recent update to PyO3 v0.21.2 or the various improvements in Yrs.

**Comment by davidbrochart** [comment]
Released in v2.1.2.

**Pull request merged**
