### PR TITLE
Fix concurrent room initialization

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Review by Zsailer — APPROVED** [review]
Thanks, @davidbrochart. This looks good to me.

**Comment by Zsailer** [comment]
> I should mention that this PR not only has a test, but also a fix.

Yeah, I saw this. 

No objection. This makes sense to me. I'm not sure how this affects @dlqqq's PR. Perhaps some of this logic will change in #250, but for now this makes sense.

**Comment by Zsailer** [comment]
I'm kicking the CI really fast to see if the flaky windows test passes and triggers the remaining tests. 

I think the UI tests are failing in other PRs, so I think we can ignore here.

**Comment by Zsailer** [comment]
The windows 3.8 test seems to fail reliably. I've kicked it 3 times and it keeps failing. @davidbrochart can you check if it's related to your changes?

**Comment by davidbrochart** [comment]
> I'm not sure how this affects @dlqqq's PR. Perhaps some of this logic will change in #250, but for now this makes sense.

Yes if #250 gets merged it will override the changes in this PR, but until then let's release since it fixes a bug.

**Pull request merged**
