### PR TITLE
Remove the unused `ISettingRegistry` token from the file browser plugin

### PR DESCRIPTION
**Pull request by trungleduc**
3.0.0b5 is broken due to this token.

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Good catch, thanks!

**Comment by jtpio** [comment]
`check-links` seems to be failing consistently and can likely be tracked separately.

**Comment by trungleduc** [comment]
Thanks @jtpio, could you trigger the release action? The current version is broken

**Comment by davidbrochart** [comment]
Done.

**Comment by krassowski** [comment]
In an unlikely circumstance if anyone else finds them bitten by this - the error on the server side would be:

```
tornado.web.HTTPError: HTTP 404: Not Found (Settings not found (jupyterlab))
```

because the `.load('jupyter')` method was called on settings registry, not on translator. In UI the consequence was that the file browser was not showing up.

Thanks for the quick fix!

Should we add a snapshot test for filebrowser showing up?

**Pull request merged**
