### PR TITLE
Test suggestion PR

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Comment by trungleduc** [comment]
Hmm, there is no conflict but the diff is still showing the code existing on main.

**Comment by davidbrochart** [comment]
Yes I was expecting something like that.

**Comment by trungleduc** [comment]
If we keep using backport PRs but do the rebase when we decide to merge `suggession` to `main`, it should be ok?

**Comment by davidbrochart** [comment]
Could you try to rebase locally, and see how it goes?

**Comment by trungleduc** [comment]
> Could you try to rebase locally, and see how it goes?

it's the same as rebase without the backport PR

**Comment by trungleduc** [comment]
but I agree It's cleaner by rebasing regularly the `suggestions` branch

**Comment by davidbrochart** [comment]
> but I agree It's cleaner by rebasing regularly the `suggestions` branch

I would prefer doing that, maybe we can allow it on the `suggestions` branch, or we do it on our forks?

**Comment by davidbrochart** [comment]
I just rebased `suggestions` on `main`, so the force-push protection rule doesn't apply to `suggestions`.
Let me see if I can give you rights on this repo.

**Comment by davidbrochart** [comment]
I gave you maintainer rights, if it's not enough I'll give you admin rights.

**Comment by trungleduc** [comment]
Great! Thanks

**Pull request closed without merging**
