### PR TITLE
Update with jupyter-ydoc v3.0.2

### PR DESCRIPTION
**Pull request by davidbrochart**
This should use jupyter-ydoc [v3.0.2](https://github.com/jupyter-server/jupyter_ydoc/releases/tag/v3.0.2), and UI tests should fail because we updated the snapshots [here](https://github.com/jupyterlab/jupyter-collaboration/pull/396#issuecomment-2457755251).

### CODE REVIEW

**Comment by trungleduc** [comment]
please update snapshots

**Comment by krassowski** [comment]
It looks like the tests did not fail here even though 3.0.2 was installed?

I see jupyter_ydoc-3.0.2-py3-none-any.whl is used.

**Comment by davidbrochart** [comment]
Indeed, I don't understand.

**Comment by davidbrochart** [comment]
Oh but running UI tests locally I see that the text is rendered in one line, maybe we changed the snapshots again after #396?

**Comment by trungleduc** [comment]
it looks ok now

**Comment by trungleduc** [comment]
please update snapshots

**Comment by davidbrochart** [comment]
> it looks ok now

But there are 4 failed tests now?

**Comment by davidbrochart** [comment]
It's hard to believe that lowering `maxDiffPixelRatio` makes the test fail, otherwise we were not testing anything before? The difference was huge, because we had a text in one column instead of one line.

**Comment by davidbrochart** [comment]
The updated snapshots look good:
image

But isn't it revealing an issue in the tests themselves?

**Comment by trungleduc** [comment]
> It's hard to believe that lowering `maxDiffPixelRatio` makes the test fail, otherwise we were not testing anything before? The difference was huge, because we had a text in one column instead of one line.

the diff is computed by the number of changed pixels, so maybe for the text, the diff is big but not too much in terms of pixel number.

**Comment by trungleduc** [comment]
> Fair enough, but then tests should likely not have failed in #396 too.

yeah, flakiness is the beauty of the UI tests.

**Comment by krassowski** [comment]
What do you think about excluding 3.0.0 and 3.0.1 from dependencies using `!=` in:

https://github.com/jupyterlab/jupyter-collaboration/blob/ed544ba982f55d1fd4a28d5124fbddc3043bbf89/projects/jupyter-server-ydoc/pyproject.toml#L32

**Comment by davidbrochart** [comment]
Good point, let's do it.

**Pull request merged**
