### PR TITLE
Fix mypy

### PR DESCRIPTION
**Pull request by brichet**
This PR should fix mypy which fails with the `bump_version.py` file.

### CODE REVIEW

**Review by davidbrochart — APPROVED** [review]
Thanks, failures are unrelated, let's fix them in another PR.

**Comment by davidbrochart** [comment]
Wait, pre-commit is still failing? It means mypy is still analysing this file? Also, we don't need `# type: ignore` anymore:
```py
from pkg_resources import parse_version  # type: ignore
```

**Comment by brichet** [comment]
> Wait, pre-commit is still failing? It means mypy is still analysing this file? 

Yes, I saw that...

> Also, we don't need `# type: ignore` anymore:
> 
> ```python
> from pkg_resources import parse_version  # type: ignore
> ```

The 2 first commits that I reverted fixed mypy for that file.

**Comment by brichet** [comment]
Thanks @davidbrochart.

Should we remove 
```exclude=[
    "^binder/jupyter_config\\.py$",
    "^scripts/bump_version\\.py$",
    "/setup\\.py$",
]
```
from *pyproject.toml* to avoid confusion, or is this useful for local run ?

**Comment by davidbrochart** [comment]
Yes I think it's still useful outside of pre-commit.

**Pull request merged**
