### PR TITLE
Fix open path error with timeline feature

### PR DESCRIPTION
**Pull request by Meriem-BenIsmail**
This PR fixes https://github.com/jupyterlab/jupyter-collaboration/issues/392

### CODE REVIEW

**Comment by davidbrochart** [comment]
I just rebases on `main`.

**Comment by Meriem-BenIsmail** [comment]
I have a clarification request concerning this PR for fixing the https://github.com/jupyterlab/jupyter-collaboration/issues/392 issue. 
If we choose to open a notebook with the 'Open from Path' option, it doesn't open the notebook in collaborative mode (without the RTC prefix) so the timeline slider (also the history icon) shouldn't even be visible if it's not collaborative. That's what I did in this PR so that the history icon wouldn't be shown and the error described in this issue https://github.com/jupyterlab/jupyter-collaboration/issues/392 wouldn't occur. I wanted to check if that's the expected behavior that the timeline should have.

**Comment by davidbrochart** [comment]
I agree that if we "Open from Path" e.g. "Untitled.ipynb", the file should not be opened in collaborative mode, and thus no timeline should be available. But if we "Open from Path" e.g. "RTC:Untitled.ipynb", the file should be opened in collaborative mode, and the timeline should be available.

**Review by davidbrochart — APPROVED** [review]
Thanks @Meriem-BenIsmail.

**Pull request merged**
