### PR TITLE
Update JupyterLab 4.2.0 and fix test start store

### PR DESCRIPTION
**Pull request by davidbrochart**
After https://github.com/jupyter-server/pycrdt-websocket/pull/42, `main` is broken, see [here](https://github.com/jupyterlab/jupyter-collaboration/actions/runs/8983746606/job/24674144833).

### CODE REVIEW

**Comment by davidbrochart** [comment]
Looks like failures are related to JupyterLab 4.2.0.
cc @krassowski @fcollonval

**Comment by krassowski** [comment]
I think two things need to be done:
- currently the packages pin to alpha versions of JupyterLab 4.2.0 - these need to be bumped for the "outdated packages" failing check to go away
- the snapshots will need to be updated to include the updated UI elements from JupyterLab 4.2.0

**Comment by davidbrochart** [comment]
Thanks @krassowski, I opened #306.

**Comment by davidbrochart** [comment]
I rebased this PR on #306.

**Comment by davidbrochart** [comment]
Finally got it working :smile: 
Do you want to review @krassowski ?

**Pull request merged**
