### PR TITLE
[2.x] Support @jupyter/ydoc 2.x

### LINKED ISSUE #309: 2.1.1 shows jupyterlab compatibility warning with jupyterlab 4.2
## Description

Noted on https://github.com/conda-forge/jupyter-collaboration-feedstock/pull/12#issuecomment-2101774026, the basic smoke test is failing for whether a user might see (or perceive) problems with their jupyterlab versions. Given the nature and complexity of this extension (and the changes in lab 4.1+), I would surprised if the `4.0.x` versions in `yarn.lock` _weren't_ masking some typescript-level issues. Indeed has been [pinned](https://github.com/jupyterlab/jupyter-collaboration/commit/e5ab770ebe976e119efd121ed2486ab07b10cdc3), which is suspicious if not also provided as runtime constraints so users' package managers benefit from this wisdom in a meaningful way.

```
+ jupyter labextension list
JupyterLab v4.2.0
/home/conda/feedstock_root/build_artifacts/jupyter-collaboration_1715216099941/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter/collaboration-extension v2.1.1 enabled  X (python, jupyter_collaboration)


   The following extensions may be outdated or specify dependencies that are incompatible with the current version of jupyterlab:
        @jupyter/collaboration-extension
        
   If you are a user, check if an update is available for these packages.
   If you are a developer, re-run with `--verbose` flag for more details.


Disabled extensions:
    @jupyterlab/filebrowser-extension:defaultFileBrowser

```

## Reproduce

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=930358&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=935

## Expected behavior

```
@jupyter/collaboration-extension v2.1.1 enabled  OK (python, jupyter_collaboration)
```

## Context

- Operating System and version: Linux Centos 7
- Browser and version: n/a
- JupyterLab version: 4.2.0

```
    jupyter-collaboration:         2.1.1-pyhd8ed1ab_0          local      
    jupyter-lsp:                   2.2.5-pyhd8ed1ab_0          conda-forge
    jupyter_client:                8.6.1-pyhd8ed1ab_0          conda-forge
    jupyter_core:                  5.7.2-py312h7900ff3_0       conda-forge
    jupyter_events:                0.10.0-pyhd8ed1ab_0         conda-forge
    jupyter_server:                2.14.0-pyhd8ed1ab_0         conda-forge
    jupyter_server_fileid:         0.9.2-pyhd8ed1ab_0          conda-forge
    jupyter_server_terminals:      0.5.3-pyhd8ed1ab_0          conda-forge
    jupyter_ydoc:                  2.0.1-pyhd8ed1ab_0          conda-forge
    jupyterlab:                    4.2.0-pyhd8ed1ab_0          conda-forge
    jupyterlab_pygments:           0.3.0-pyhd8ed1ab_1          conda-forge
    jupyterlab_server:             2.27.1-pyhd8ed1ab_0         conda-forge
 
```

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #309

@jupyter/ydoc 2.x is identical to 1.x - the major bump was a consequence of a change in the Python package.

### CODE REVIEW

**Review by davidbrochart — APPROVED** [review]
Thanks Fred.

**Comment by fcollonval** [comment]
On Binder build, the result of `jupyter labextension list` is

```
+ jupyter labextension list
JupyterLab v4.2.1
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.2 enabled  X
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.10 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v1.0.2 enabled OK (python, jupyter-resource-usage)
        @jupyter/collaboration-extension v2.1.1 enabled OK (python, jupyter_collaboration)


   The following extensions may be outdated or specify dependencies that are incompatible with the current version of jupyterlab:
        jupyter-offlinenotebook
        
   If you are a user, check if an update is available for these packages.
   If you are a developer, re-run with `--verbose` flag for more details.


Disabled extensions:
    @jupyterlab/filebrowser-extension:defaultFileBrowser
```

**Comment by davidbrochart** [comment]
This is happening in `pycrdt-websocket`.
Another (temporary) option would be to pin `anyio <4.4.0`.

**Comment by fcollonval** [comment]
> Failures seem to be caused by the latest release of AnyIO. In this [PR](https://github.com/agronholm/anyio/pull/715), AnyIO now emits a `ResourceWarning` on unclosed memory object streams. So we should either explicitly close memory object streams (best) or ignore this warning in tests.

Thanks for highlighting the source of the error. I add the new warning to the ignore list of pytest in 4a311c7.

**Comment by davidbrochart** [comment]
Thanks. I guess we should update the screenshots in the UI tests, as we did in `3.x`?

**Comment by davidbrochart** [comment]
@fcollonval there are conflicts, sorry for not merging earlier. Do you want to rebase?

**Comment by brichet** [comment]
@fcollonval I can rebase it if you want, I also need this compatibility.

**Comment by fcollonval** [comment]
> @fcollonval I can rebase it if you want, I also need this compatibility.

Thanks @brichet please feel free to do so. My oss bandwidth is tight currently.

**Comment by brichet** [comment]
Failing tests seem not related to this PR.

**Review by davidbrochart — APPROVED** [review]
Thanks.

**Pull request merged**
