### PR TITLE
Update CI (#396)

### PR DESCRIPTION
**Pull request by trungleduc**
Backport #396

### CODE REVIEW

**Comment by davidbrochart** [comment]
Should we just rebase the `suggestions` branch on `main` instead of creating a PR?

**Comment by trungleduc** [comment]
> Should we just rebase the `suggestions` branch on `main` instead of creating a PR?

I don't have the right to rebase this branch. It would be great if you could set up the backport bot.

**Comment by davidbrochart** [comment]
But even if we set up a backport bot, we will end up with a bunch of commits that are different from `main`, right?

**Comment by trungleduc** [comment]
yep, but at least I don't need to ask you to rebase this branch every time.

**Comment by trungleduc** [comment]
@davidbrochart let's merge this?

**Comment by jtpio** [comment]
@meeseeksdev hello

(to test if the bot is enabled here)

**Comment by davidbrochart** [comment]
> @davidbrochart let's merge this?

I'm just a bit worried about when we merge branch `suggestions` into `main`. Won't we get a bunch of conflicts?

**Comment by trungleduc** [comment]
> > @davidbrochart let's merge this?
> 
> I'm just a bit worried about when we merge branch `suggestions` into `main`. Won't we get a bunch of conflicts?

Theoretically no since we resolve conflicts on each backport PR.

**Comment by davidbrochart** [comment]
I agree that the diff should only be our code, but I think the backport PRs will still be seen as conflicts.
Anyway, let's see with this one as you said :+1:

**Pull request merged**
